export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_ACTIVE_SPECIALTY_FILTERS = 'SET_ACTIVE_SPECIALTY_FILTERS';
export const TOGGLE_SPECIALTY_FILTER = 'TOGGLE_SPECIALTY_FILTER';
export const SET_PROVIDERS_BY_LOCATION_FILTER =
  'SET_PROVIDERS_BY_LOCATION_FILTER';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_PROVIDER_NAME_FILTER = 'SET_PROVIDER_NAME_FILTER';
